#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBMA1")]
	public partial class VanchBgDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchat_record(chat_record instance);
    partial void Updatechat_record(chat_record instance);
    partial void Deletechat_record(chat_record instance);
    partial void Insertconfig(config instance);
    partial void Updateconfig(config instance);
    partial void Deleteconfig(config instance);
    partial void Insertinternal_user(internal_user instance);
    partial void Updateinternal_user(internal_user instance);
    partial void Deleteinternal_user(internal_user instance);
    partial void Insertuser_group(user_group instance);
    partial void Updateuser_group(user_group instance);
    partial void Deleteuser_group(user_group instance);
    partial void Insertuser_group_menu(user_group_menu instance);
    partial void Updateuser_group_menu(user_group_menu instance);
    partial void Deleteuser_group_menu(user_group_menu instance);
    partial void Insertmenu(menu instance);
    partial void Updatemenu(menu instance);
    partial void Deletemenu(menu instance);
    partial void InsertB005(B005 instance);
    partial void UpdateB005(B005 instance);
    partial void DeleteB005(B005 instance);
    partial void InsertU000(U000 instance);
    partial void UpdateU000(U000 instance);
    partial void DeleteU000(U000 instance);
    #endregion
		
		public VanchBgDataContext() : 
				base(global::DAL.Properties.Settings.Default.DBMA1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VanchBgDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VanchBgDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VanchBgDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VanchBgDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chat_record> chat_records
		{
			get
			{
				return this.GetTable<chat_record>();
			}
		}
		
		public System.Data.Linq.Table<config> configs
		{
			get
			{
				return this.GetTable<config>();
			}
		}
		
		public System.Data.Linq.Table<internal_user> internal_users
		{
			get
			{
				return this.GetTable<internal_user>();
			}
		}
		
		public System.Data.Linq.Table<user_group> user_groups
		{
			get
			{
				return this.GetTable<user_group>();
			}
		}
		
		public System.Data.Linq.Table<user_group_menu> user_group_menus
		{
			get
			{
				return this.GetTable<user_group_menu>();
			}
		}
		
		public System.Data.Linq.Table<menu> menus
		{
			get
			{
				return this.GetTable<menu>();
			}
		}
		
		public System.Data.Linq.Table<B005> B005s
		{
			get
			{
				return this.GetTable<B005>();
			}
		}
		
		public System.Data.Linq.Table<U000> U000s
		{
			get
			{
				return this.GetTable<U000>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chat_records")]
	public partial class chat_record : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _chat_records_id;
		
		private string _user_num;
		
		private string _cus_svr_num;
		
		private string _user_send_msg;
		
		private string _cus_svr_send_msg;
		
		private System.Nullable<System.DateTime> _date_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchat_records_idChanging(int value);
    partial void Onchat_records_idChanged();
    partial void Onuser_numChanging(string value);
    partial void Onuser_numChanged();
    partial void Oncus_svr_numChanging(string value);
    partial void Oncus_svr_numChanged();
    partial void Onuser_send_msgChanging(string value);
    partial void Onuser_send_msgChanged();
    partial void Oncus_svr_send_msgChanging(string value);
    partial void Oncus_svr_send_msgChanged();
    partial void Ondate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_timeChanged();
    #endregion
		
		public chat_record()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chat_records_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int chat_records_id
		{
			get
			{
				return this._chat_records_id;
			}
			set
			{
				if ((this._chat_records_id != value))
				{
					this.Onchat_records_idChanging(value);
					this.SendPropertyChanging();
					this._chat_records_id = value;
					this.SendPropertyChanged("chat_records_id");
					this.Onchat_records_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_num", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string user_num
		{
			get
			{
				return this._user_num;
			}
			set
			{
				if ((this._user_num != value))
				{
					this.Onuser_numChanging(value);
					this.SendPropertyChanging();
					this._user_num = value;
					this.SendPropertyChanged("user_num");
					this.Onuser_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_svr_num", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string cus_svr_num
		{
			get
			{
				return this._cus_svr_num;
			}
			set
			{
				if ((this._cus_svr_num != value))
				{
					this.Oncus_svr_numChanging(value);
					this.SendPropertyChanging();
					this._cus_svr_num = value;
					this.SendPropertyChanged("cus_svr_num");
					this.Oncus_svr_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_send_msg", DbType="NChar(200)")]
		public string user_send_msg
		{
			get
			{
				return this._user_send_msg;
			}
			set
			{
				if ((this._user_send_msg != value))
				{
					this.Onuser_send_msgChanging(value);
					this.SendPropertyChanging();
					this._user_send_msg = value;
					this.SendPropertyChanged("user_send_msg");
					this.Onuser_send_msgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_svr_send_msg", DbType="NChar(200)")]
		public string cus_svr_send_msg
		{
			get
			{
				return this._cus_svr_send_msg;
			}
			set
			{
				if ((this._cus_svr_send_msg != value))
				{
					this.Oncus_svr_send_msgChanging(value);
					this.SendPropertyChanging();
					this._cus_svr_send_msg = value;
					this.SendPropertyChanged("cus_svr_send_msg");
					this.Oncus_svr_send_msgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this.Ondate_timeChanging(value);
					this.SendPropertyChanging();
					this._date_time = value;
					this.SendPropertyChanged("date_time");
					this.Ondate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.config")]
	public partial class config : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _config_id;
		
		private System.Nullable<int> _cusSvrMode;
		
		private System.Nullable<int> _cusSvrUserMaxAmount;
		
		private System.Nullable<int> _webDelay;
		
		private System.Nullable<int> _cusSvrUserDelLevel;
		
		private System.Nullable<int> _maxCusSvrConnLevel;
		
		private System.Nullable<int> _maxUserConnNum;
		
		private System.Nullable<int> _countSizeLevel;
		
		private System.Nullable<int> _showCountDownSizeLevel;
		
		private System.Nullable<int> _levelSeconds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onconfig_idChanging(int value);
    partial void Onconfig_idChanged();
    partial void OncusSvrModeChanging(System.Nullable<int> value);
    partial void OncusSvrModeChanged();
    partial void OncusSvrUserMaxAmountChanging(System.Nullable<int> value);
    partial void OncusSvrUserMaxAmountChanged();
    partial void OnwebDelayChanging(System.Nullable<int> value);
    partial void OnwebDelayChanged();
    partial void OncusSvrUserDelLevelChanging(System.Nullable<int> value);
    partial void OncusSvrUserDelLevelChanged();
    partial void OnmaxCusSvrConnLevelChanging(System.Nullable<int> value);
    partial void OnmaxCusSvrConnLevelChanged();
    partial void OnmaxUserConnNumChanging(System.Nullable<int> value);
    partial void OnmaxUserConnNumChanged();
    partial void OncountSizeLevelChanging(System.Nullable<int> value);
    partial void OncountSizeLevelChanged();
    partial void OnshowCountDownSizeLevelChanging(System.Nullable<int> value);
    partial void OnshowCountDownSizeLevelChanged();
    partial void OnlevelSecondsChanging(System.Nullable<int> value);
    partial void OnlevelSecondsChanged();
    #endregion
		
		public config()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_config_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int config_id
		{
			get
			{
				return this._config_id;
			}
			set
			{
				if ((this._config_id != value))
				{
					this.Onconfig_idChanging(value);
					this.SendPropertyChanging();
					this._config_id = value;
					this.SendPropertyChanged("config_id");
					this.Onconfig_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cusSvrMode", DbType="Int")]
		public System.Nullable<int> cusSvrMode
		{
			get
			{
				return this._cusSvrMode;
			}
			set
			{
				if ((this._cusSvrMode != value))
				{
					this.OncusSvrModeChanging(value);
					this.SendPropertyChanging();
					this._cusSvrMode = value;
					this.SendPropertyChanged("cusSvrMode");
					this.OncusSvrModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cusSvrUserMaxAmount", DbType="Int")]
		public System.Nullable<int> cusSvrUserMaxAmount
		{
			get
			{
				return this._cusSvrUserMaxAmount;
			}
			set
			{
				if ((this._cusSvrUserMaxAmount != value))
				{
					this.OncusSvrUserMaxAmountChanging(value);
					this.SendPropertyChanging();
					this._cusSvrUserMaxAmount = value;
					this.SendPropertyChanged("cusSvrUserMaxAmount");
					this.OncusSvrUserMaxAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_webDelay", DbType="Int")]
		public System.Nullable<int> webDelay
		{
			get
			{
				return this._webDelay;
			}
			set
			{
				if ((this._webDelay != value))
				{
					this.OnwebDelayChanging(value);
					this.SendPropertyChanging();
					this._webDelay = value;
					this.SendPropertyChanged("webDelay");
					this.OnwebDelayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cusSvrUserDelLevel", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> cusSvrUserDelLevel
		{
			get
			{
				return this._cusSvrUserDelLevel;
			}
			set
			{
				if ((this._cusSvrUserDelLevel != value))
				{
					this.OncusSvrUserDelLevelChanging(value);
					this.SendPropertyChanging();
					this._cusSvrUserDelLevel = value;
					this.SendPropertyChanged("cusSvrUserDelLevel");
					this.OncusSvrUserDelLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxCusSvrConnLevel", DbType="Int")]
		public System.Nullable<int> maxCusSvrConnLevel
		{
			get
			{
				return this._maxCusSvrConnLevel;
			}
			set
			{
				if ((this._maxCusSvrConnLevel != value))
				{
					this.OnmaxCusSvrConnLevelChanging(value);
					this.SendPropertyChanging();
					this._maxCusSvrConnLevel = value;
					this.SendPropertyChanged("maxCusSvrConnLevel");
					this.OnmaxCusSvrConnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxUserConnNum", DbType="Int")]
		public System.Nullable<int> maxUserConnNum
		{
			get
			{
				return this._maxUserConnNum;
			}
			set
			{
				if ((this._maxUserConnNum != value))
				{
					this.OnmaxUserConnNumChanging(value);
					this.SendPropertyChanging();
					this._maxUserConnNum = value;
					this.SendPropertyChanged("maxUserConnNum");
					this.OnmaxUserConnNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countSizeLevel", DbType="Int")]
		public System.Nullable<int> countSizeLevel
		{
			get
			{
				return this._countSizeLevel;
			}
			set
			{
				if ((this._countSizeLevel != value))
				{
					this.OncountSizeLevelChanging(value);
					this.SendPropertyChanging();
					this._countSizeLevel = value;
					this.SendPropertyChanged("countSizeLevel");
					this.OncountSizeLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_showCountDownSizeLevel", DbType="Int")]
		public System.Nullable<int> showCountDownSizeLevel
		{
			get
			{
				return this._showCountDownSizeLevel;
			}
			set
			{
				if ((this._showCountDownSizeLevel != value))
				{
					this.OnshowCountDownSizeLevelChanging(value);
					this.SendPropertyChanging();
					this._showCountDownSizeLevel = value;
					this.SendPropertyChanged("showCountDownSizeLevel");
					this.OnshowCountDownSizeLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_levelSeconds", DbType="Int")]
		public System.Nullable<int> levelSeconds
		{
			get
			{
				return this._levelSeconds;
			}
			set
			{
				if ((this._levelSeconds != value))
				{
					this.OnlevelSecondsChanging(value);
					this.SendPropertyChanging();
					this._levelSeconds = value;
					this.SendPropertyChanged("levelSeconds");
					this.OnlevelSecondsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.internal_user")]
	public partial class internal_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _internal_user_id;
		
		private string _work_num;
		
		private string _pwd;
		
		private string _name;
		
		private System.Nullable<bool> _gender;
		
		private System.Nullable<System.DateTime> _reg_date;
		
		private string _department_name;
		
		private string _jobs;
		
		private string _user_group;
		
		private System.Nullable<int> _fk_user_group_id;
		
		private System.Nullable<System.DateTime> _allocate_date;
		
		private string _operater;
		
		private char _use_status;
		
		private EntitySet<B005> _B005s;
		
		private EntityRef<user_group> _user_group1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oninternal_user_idChanging(int value);
    partial void Oninternal_user_idChanged();
    partial void Onwork_numChanging(string value);
    partial void Onwork_numChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngenderChanging(System.Nullable<bool> value);
    partial void OngenderChanged();
    partial void Onreg_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onreg_dateChanged();
    partial void Ondepartment_nameChanging(string value);
    partial void Ondepartment_nameChanged();
    partial void OnjobsChanging(string value);
    partial void OnjobsChanged();
    partial void Onuser_groupChanging(string value);
    partial void Onuser_groupChanged();
    partial void Onfk_user_group_idChanging(System.Nullable<int> value);
    partial void Onfk_user_group_idChanged();
    partial void Onallocate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onallocate_dateChanged();
    partial void OnoperaterChanging(string value);
    partial void OnoperaterChanged();
    partial void Onuse_statusChanging(char value);
    partial void Onuse_statusChanged();
    #endregion
		
		public internal_user()
		{
			this._B005s = new EntitySet<B005>(new Action<B005>(this.attach_B005s), new Action<B005>(this.detach_B005s));
			this._user_group1 = default(EntityRef<user_group>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_internal_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int internal_user_id
		{
			get
			{
				return this._internal_user_id;
			}
			set
			{
				if ((this._internal_user_id != value))
				{
					this.Oninternal_user_idChanging(value);
					this.SendPropertyChanging();
					this._internal_user_id = value;
					this.SendPropertyChanged("internal_user_id");
					this.Oninternal_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_work_num", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string work_num
		{
			get
			{
				return this._work_num;
			}
			set
			{
				if ((this._work_num != value))
				{
					this.Onwork_numChanging(value);
					this.SendPropertyChanging();
					this._work_num = value;
					this.SendPropertyChanged("work_num");
					this.Onwork_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this.OnpwdChanging(value);
					this.SendPropertyChanging();
					this._pwd = value;
					this.SendPropertyChanged("pwd");
					this.OnpwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reg_date", DbType="Date")]
		public System.Nullable<System.DateTime> reg_date
		{
			get
			{
				return this._reg_date;
			}
			set
			{
				if ((this._reg_date != value))
				{
					this.Onreg_dateChanging(value);
					this.SendPropertyChanging();
					this._reg_date = value;
					this.SendPropertyChanged("reg_date");
					this.Onreg_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_name", DbType="NChar(20)")]
		public string department_name
		{
			get
			{
				return this._department_name;
			}
			set
			{
				if ((this._department_name != value))
				{
					this.Ondepartment_nameChanging(value);
					this.SendPropertyChanging();
					this._department_name = value;
					this.SendPropertyChanged("department_name");
					this.Ondepartment_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobs", DbType="NChar(20)")]
		public string jobs
		{
			get
			{
				return this._jobs;
			}
			set
			{
				if ((this._jobs != value))
				{
					this.OnjobsChanging(value);
					this.SendPropertyChanging();
					this._jobs = value;
					this.SendPropertyChanged("jobs");
					this.OnjobsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_group", DbType="NChar(20)")]
		public string user_group
		{
			get
			{
				return this._user_group;
			}
			set
			{
				if ((this._user_group != value))
				{
					this.Onuser_groupChanging(value);
					this.SendPropertyChanging();
					this._user_group = value;
					this.SendPropertyChanged("user_group");
					this.Onuser_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_user_group_id", DbType="Int")]
		public System.Nullable<int> fk_user_group_id
		{
			get
			{
				return this._fk_user_group_id;
			}
			set
			{
				if ((this._fk_user_group_id != value))
				{
					if (this._user_group1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_user_group_idChanging(value);
					this.SendPropertyChanging();
					this._fk_user_group_id = value;
					this.SendPropertyChanged("fk_user_group_id");
					this.Onfk_user_group_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allocate_date", DbType="Date")]
		public System.Nullable<System.DateTime> allocate_date
		{
			get
			{
				return this._allocate_date;
			}
			set
			{
				if ((this._allocate_date != value))
				{
					this.Onallocate_dateChanging(value);
					this.SendPropertyChanging();
					this._allocate_date = value;
					this.SendPropertyChanged("allocate_date");
					this.Onallocate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operater", DbType="NVarChar(50)")]
		public string operater
		{
			get
			{
				return this._operater;
			}
			set
			{
				if ((this._operater != value))
				{
					this.OnoperaterChanging(value);
					this.SendPropertyChanging();
					this._operater = value;
					this.SendPropertyChanged("operater");
					this.OnoperaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_use_status", DbType="Char(1) NOT NULL")]
		public char use_status
		{
			get
			{
				return this._use_status;
			}
			set
			{
				if ((this._use_status != value))
				{
					this.Onuse_statusChanging(value);
					this.SendPropertyChanging();
					this._use_status = value;
					this.SendPropertyChanged("use_status");
					this.Onuse_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="internal_user_B005", Storage="_B005s", ThisKey="internal_user_id", OtherKey="internalUserSN")]
		public EntitySet<B005> B005s
		{
			get
			{
				return this._B005s;
			}
			set
			{
				this._B005s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_group_internal_user", Storage="_user_group1", ThisKey="fk_user_group_id", OtherKey="user_group_id", IsForeignKey=true)]
		public user_group user_group1
		{
			get
			{
				return this._user_group1.Entity;
			}
			set
			{
				user_group previousValue = this._user_group1.Entity;
				if (((previousValue != value) 
							|| (this._user_group1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user_group1.Entity = null;
						previousValue.internal_users.Remove(this);
					}
					this._user_group1.Entity = value;
					if ((value != null))
					{
						value.internal_users.Add(this);
						this._fk_user_group_id = value.user_group_id;
					}
					else
					{
						this._fk_user_group_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("user_group1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_B005s(B005 entity)
		{
			this.SendPropertyChanging();
			entity.internal_user = this;
		}
		
		private void detach_B005s(B005 entity)
		{
			this.SendPropertyChanging();
			entity.internal_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_group")]
	public partial class user_group : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_group_id;
		
		private string _user_group_name;
		
		private System.Nullable<System.DateTime> _delete_date;
		
		private EntitySet<internal_user> _internal_users;
		
		private EntitySet<user_group_menu> _user_group_menus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_group_idChanging(int value);
    partial void Onuser_group_idChanged();
    partial void Onuser_group_nameChanging(string value);
    partial void Onuser_group_nameChanged();
    partial void Ondelete_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondelete_dateChanged();
    #endregion
		
		public user_group()
		{
			this._internal_users = new EntitySet<internal_user>(new Action<internal_user>(this.attach_internal_users), new Action<internal_user>(this.detach_internal_users));
			this._user_group_menus = new EntitySet<user_group_menu>(new Action<user_group_menu>(this.attach_user_group_menus), new Action<user_group_menu>(this.detach_user_group_menus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_group_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_group_id
		{
			get
			{
				return this._user_group_id;
			}
			set
			{
				if ((this._user_group_id != value))
				{
					this.Onuser_group_idChanging(value);
					this.SendPropertyChanging();
					this._user_group_id = value;
					this.SendPropertyChanged("user_group_id");
					this.Onuser_group_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_group_name", DbType="NVarChar(50)")]
		public string user_group_name
		{
			get
			{
				return this._user_group_name;
			}
			set
			{
				if ((this._user_group_name != value))
				{
					this.Onuser_group_nameChanging(value);
					this.SendPropertyChanging();
					this._user_group_name = value;
					this.SendPropertyChanged("user_group_name");
					this.Onuser_group_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_date", DbType="Date")]
		public System.Nullable<System.DateTime> delete_date
		{
			get
			{
				return this._delete_date;
			}
			set
			{
				if ((this._delete_date != value))
				{
					this.Ondelete_dateChanging(value);
					this.SendPropertyChanging();
					this._delete_date = value;
					this.SendPropertyChanged("delete_date");
					this.Ondelete_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_group_internal_user", Storage="_internal_users", ThisKey="user_group_id", OtherKey="fk_user_group_id")]
		public EntitySet<internal_user> internal_users
		{
			get
			{
				return this._internal_users;
			}
			set
			{
				this._internal_users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_group_user_group_menu", Storage="_user_group_menus", ThisKey="user_group_id", OtherKey="fk_user_group_id")]
		public EntitySet<user_group_menu> user_group_menus
		{
			get
			{
				return this._user_group_menus;
			}
			set
			{
				this._user_group_menus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_internal_users(internal_user entity)
		{
			this.SendPropertyChanging();
			entity.user_group1 = this;
		}
		
		private void detach_internal_users(internal_user entity)
		{
			this.SendPropertyChanging();
			entity.user_group1 = null;
		}
		
		private void attach_user_group_menus(user_group_menu entity)
		{
			this.SendPropertyChanging();
			entity.user_group = this;
		}
		
		private void detach_user_group_menus(user_group_menu entity)
		{
			this.SendPropertyChanging();
			entity.user_group = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_group_menu")]
	public partial class user_group_menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_group_menu_id;
		
		private int _fk_user_group_id;
		
		private int _fk_menu_id;
		
		private System.Nullable<System.DateTime> _delete_date;
		
		private EntityRef<user_group> _user_group;
		
		private EntityRef<menu> _menu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_group_menu_idChanging(int value);
    partial void Onuser_group_menu_idChanged();
    partial void Onfk_user_group_idChanging(int value);
    partial void Onfk_user_group_idChanged();
    partial void Onfk_menu_idChanging(int value);
    partial void Onfk_menu_idChanged();
    partial void Ondelete_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondelete_dateChanged();
    #endregion
		
		public user_group_menu()
		{
			this._user_group = default(EntityRef<user_group>);
			this._menu = default(EntityRef<menu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_group_menu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_group_menu_id
		{
			get
			{
				return this._user_group_menu_id;
			}
			set
			{
				if ((this._user_group_menu_id != value))
				{
					this.Onuser_group_menu_idChanging(value);
					this.SendPropertyChanging();
					this._user_group_menu_id = value;
					this.SendPropertyChanged("user_group_menu_id");
					this.Onuser_group_menu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_user_group_id", DbType="Int NOT NULL")]
		public int fk_user_group_id
		{
			get
			{
				return this._fk_user_group_id;
			}
			set
			{
				if ((this._fk_user_group_id != value))
				{
					if (this._user_group.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_user_group_idChanging(value);
					this.SendPropertyChanging();
					this._fk_user_group_id = value;
					this.SendPropertyChanged("fk_user_group_id");
					this.Onfk_user_group_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_menu_id", DbType="Int NOT NULL")]
		public int fk_menu_id
		{
			get
			{
				return this._fk_menu_id;
			}
			set
			{
				if ((this._fk_menu_id != value))
				{
					if (this._menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_menu_idChanging(value);
					this.SendPropertyChanging();
					this._fk_menu_id = value;
					this.SendPropertyChanged("fk_menu_id");
					this.Onfk_menu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_date", DbType="Date")]
		public System.Nullable<System.DateTime> delete_date
		{
			get
			{
				return this._delete_date;
			}
			set
			{
				if ((this._delete_date != value))
				{
					this.Ondelete_dateChanging(value);
					this.SendPropertyChanging();
					this._delete_date = value;
					this.SendPropertyChanged("delete_date");
					this.Ondelete_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_group_user_group_menu", Storage="_user_group", ThisKey="fk_user_group_id", OtherKey="user_group_id", IsForeignKey=true)]
		public user_group user_group
		{
			get
			{
				return this._user_group.Entity;
			}
			set
			{
				user_group previousValue = this._user_group.Entity;
				if (((previousValue != value) 
							|| (this._user_group.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user_group.Entity = null;
						previousValue.user_group_menus.Remove(this);
					}
					this._user_group.Entity = value;
					if ((value != null))
					{
						value.user_group_menus.Add(this);
						this._fk_user_group_id = value.user_group_id;
					}
					else
					{
						this._fk_user_group_id = default(int);
					}
					this.SendPropertyChanged("user_group");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="menu_user_group_menu", Storage="_menu", ThisKey="fk_menu_id", OtherKey="menu_id", IsForeignKey=true)]
		public menu menu
		{
			get
			{
				return this._menu.Entity;
			}
			set
			{
				menu previousValue = this._menu.Entity;
				if (((previousValue != value) 
							|| (this._menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._menu.Entity = null;
						previousValue.user_group_menus.Remove(this);
					}
					this._menu.Entity = value;
					if ((value != null))
					{
						value.user_group_menus.Add(this);
						this._fk_menu_id = value.menu_id;
					}
					else
					{
						this._fk_menu_id = default(int);
					}
					this.SendPropertyChanged("menu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.menu")]
	public partial class menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _menu_id;
		
		private string _menu_code;
		
		private string _parent_menu_code;
		
		private string _menu_parent_title;
		
		private string _menu_title;
		
		private string _module_code;
		
		private string _element_version;
		
		private string _control_version;
		
		private System.Nullable<int> _sequence;
		
		private EntitySet<user_group_menu> _user_group_menus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmenu_idChanging(int value);
    partial void Onmenu_idChanged();
    partial void Onmenu_codeChanging(string value);
    partial void Onmenu_codeChanged();
    partial void Onparent_menu_codeChanging(string value);
    partial void Onparent_menu_codeChanged();
    partial void Onmenu_parent_titleChanging(string value);
    partial void Onmenu_parent_titleChanged();
    partial void Onmenu_titleChanging(string value);
    partial void Onmenu_titleChanged();
    partial void Onmodule_codeChanging(string value);
    partial void Onmodule_codeChanged();
    partial void Onelement_versionChanging(string value);
    partial void Onelement_versionChanged();
    partial void Oncontrol_versionChanging(string value);
    partial void Oncontrol_versionChanged();
    partial void OnsequenceChanging(System.Nullable<int> value);
    partial void OnsequenceChanged();
    #endregion
		
		public menu()
		{
			this._user_group_menus = new EntitySet<user_group_menu>(new Action<user_group_menu>(this.attach_user_group_menus), new Action<user_group_menu>(this.detach_user_group_menus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int menu_id
		{
			get
			{
				return this._menu_id;
			}
			set
			{
				if ((this._menu_id != value))
				{
					this.Onmenu_idChanging(value);
					this.SendPropertyChanging();
					this._menu_id = value;
					this.SendPropertyChanged("menu_id");
					this.Onmenu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_code", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string menu_code
		{
			get
			{
				return this._menu_code;
			}
			set
			{
				if ((this._menu_code != value))
				{
					this.Onmenu_codeChanging(value);
					this.SendPropertyChanging();
					this._menu_code = value;
					this.SendPropertyChanged("menu_code");
					this.Onmenu_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_menu_code", DbType="VarChar(5)")]
		public string parent_menu_code
		{
			get
			{
				return this._parent_menu_code;
			}
			set
			{
				if ((this._parent_menu_code != value))
				{
					this.Onparent_menu_codeChanging(value);
					this.SendPropertyChanging();
					this._parent_menu_code = value;
					this.SendPropertyChanged("parent_menu_code");
					this.Onparent_menu_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_parent_title", DbType="NVarChar(50)")]
		public string menu_parent_title
		{
			get
			{
				return this._menu_parent_title;
			}
			set
			{
				if ((this._menu_parent_title != value))
				{
					this.Onmenu_parent_titleChanging(value);
					this.SendPropertyChanging();
					this._menu_parent_title = value;
					this.SendPropertyChanged("menu_parent_title");
					this.Onmenu_parent_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string menu_title
		{
			get
			{
				return this._menu_title;
			}
			set
			{
				if ((this._menu_title != value))
				{
					this.Onmenu_titleChanging(value);
					this.SendPropertyChanging();
					this._menu_title = value;
					this.SendPropertyChanged("menu_title");
					this.Onmenu_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_code", DbType="VarChar(50)")]
		public string module_code
		{
			get
			{
				return this._module_code;
			}
			set
			{
				if ((this._module_code != value))
				{
					this.Onmodule_codeChanging(value);
					this.SendPropertyChanging();
					this._module_code = value;
					this.SendPropertyChanged("module_code");
					this.Onmodule_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_element_version", DbType="VarChar(50)")]
		public string element_version
		{
			get
			{
				return this._element_version;
			}
			set
			{
				if ((this._element_version != value))
				{
					this.Onelement_versionChanging(value);
					this.SendPropertyChanging();
					this._element_version = value;
					this.SendPropertyChanged("element_version");
					this.Onelement_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_control_version", DbType="VarChar(50)")]
		public string control_version
		{
			get
			{
				return this._control_version;
			}
			set
			{
				if ((this._control_version != value))
				{
					this.Oncontrol_versionChanging(value);
					this.SendPropertyChanging();
					this._control_version = value;
					this.SendPropertyChanged("control_version");
					this.Oncontrol_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sequence", DbType="Int")]
		public System.Nullable<int> sequence
		{
			get
			{
				return this._sequence;
			}
			set
			{
				if ((this._sequence != value))
				{
					this.OnsequenceChanging(value);
					this.SendPropertyChanging();
					this._sequence = value;
					this.SendPropertyChanged("sequence");
					this.OnsequenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="menu_user_group_menu", Storage="_user_group_menus", ThisKey="menu_id", OtherKey="fk_menu_id")]
		public EntitySet<user_group_menu> user_group_menus
		{
			get
			{
				return this._user_group_menus;
			}
			set
			{
				this._user_group_menus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_user_group_menus(user_group_menu entity)
		{
			this.SendPropertyChanging();
			entity.menu = this;
		}
		
		private void detach_user_group_menus(user_group_menu entity)
		{
			this.SendPropertyChanging();
			entity.menu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.B005")]
	public partial class B005 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userSN;
		
		private System.Nullable<int> _internalUserSN;
		
		private System.Nullable<System.DateTime> _assignDate;
		
		private EntityRef<internal_user> _internal_user;
		
		private EntityRef<U000> _U000;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserSNChanging(string value);
    partial void OnuserSNChanged();
    partial void OninternalUserSNChanging(System.Nullable<int> value);
    partial void OninternalUserSNChanged();
    partial void OnassignDateChanging(System.Nullable<System.DateTime> value);
    partial void OnassignDateChanged();
    #endregion
		
		public B005()
		{
			this._internal_user = default(EntityRef<internal_user>);
			this._U000 = default(EntityRef<U000>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSN", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userSN
		{
			get
			{
				return this._userSN;
			}
			set
			{
				if ((this._userSN != value))
				{
					if (this._U000.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserSNChanging(value);
					this.SendPropertyChanging();
					this._userSN = value;
					this.SendPropertyChanged("userSN");
					this.OnuserSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_internalUserSN", DbType="Int")]
		public System.Nullable<int> internalUserSN
		{
			get
			{
				return this._internalUserSN;
			}
			set
			{
				if ((this._internalUserSN != value))
				{
					if (this._internal_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OninternalUserSNChanging(value);
					this.SendPropertyChanging();
					this._internalUserSN = value;
					this.SendPropertyChanged("internalUserSN");
					this.OninternalUserSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> assignDate
		{
			get
			{
				return this._assignDate;
			}
			set
			{
				if ((this._assignDate != value))
				{
					this.OnassignDateChanging(value);
					this.SendPropertyChanging();
					this._assignDate = value;
					this.SendPropertyChanged("assignDate");
					this.OnassignDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="internal_user_B005", Storage="_internal_user", ThisKey="internalUserSN", OtherKey="internal_user_id", IsForeignKey=true)]
		public internal_user internal_user
		{
			get
			{
				return this._internal_user.Entity;
			}
			set
			{
				internal_user previousValue = this._internal_user.Entity;
				if (((previousValue != value) 
							|| (this._internal_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._internal_user.Entity = null;
						previousValue.B005s.Remove(this);
					}
					this._internal_user.Entity = value;
					if ((value != null))
					{
						value.B005s.Add(this);
						this._internalUserSN = value.internal_user_id;
					}
					else
					{
						this._internalUserSN = default(Nullable<int>);
					}
					this.SendPropertyChanged("internal_user");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="U000_B005", Storage="_U000", ThisKey="userSN", OtherKey="userSN", IsForeignKey=true)]
		public U000 U000
		{
			get
			{
				return this._U000.Entity;
			}
			set
			{
				U000 previousValue = this._U000.Entity;
				if (((previousValue != value) 
							|| (this._U000.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._U000.Entity = null;
						previousValue.B005 = null;
					}
					this._U000.Entity = value;
					if ((value != null))
					{
						value.B005 = this;
						this._userSN = value.userSN;
					}
					else
					{
						this._userSN = default(string);
					}
					this.SendPropertyChanged("U000");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.U000")]
	public partial class U000 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userSN;
		
		private string _phone;
		
		private string _pwd;
		
		private string _name;
		
		private System.DateTime _registerDate;
		
		private System.DateTime _lastLoginDate;
		
		private string _lastLoginIp;
		
		private System.Nullable<bool> _ifChangePwd;
		
		private EntityRef<B005> _B005;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserSNChanging(string value);
    partial void OnuserSNChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnregisterDateChanging(System.DateTime value);
    partial void OnregisterDateChanged();
    partial void OnlastLoginDateChanging(System.DateTime value);
    partial void OnlastLoginDateChanged();
    partial void OnlastLoginIpChanging(string value);
    partial void OnlastLoginIpChanged();
    partial void OnifChangePwdChanging(System.Nullable<bool> value);
    partial void OnifChangePwdChanged();
    #endregion
		
		public U000()
		{
			this._B005 = default(EntityRef<B005>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSN", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userSN
		{
			get
			{
				return this._userSN;
			}
			set
			{
				if ((this._userSN != value))
				{
					this.OnuserSNChanging(value);
					this.SendPropertyChanging();
					this._userSN = value;
					this.SendPropertyChanged("userSN");
					this.OnuserSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this.OnpwdChanging(value);
					this.SendPropertyChanging();
					this._pwd = value;
					this.SendPropertyChanged("pwd");
					this.OnpwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registerDate", DbType="DateTime NOT NULL")]
		public System.DateTime registerDate
		{
			get
			{
				return this._registerDate;
			}
			set
			{
				if ((this._registerDate != value))
				{
					this.OnregisterDateChanging(value);
					this.SendPropertyChanging();
					this._registerDate = value;
					this.SendPropertyChanged("registerDate");
					this.OnregisterDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastLoginDate", DbType="DateTime NOT NULL")]
		public System.DateTime lastLoginDate
		{
			get
			{
				return this._lastLoginDate;
			}
			set
			{
				if ((this._lastLoginDate != value))
				{
					this.OnlastLoginDateChanging(value);
					this.SendPropertyChanging();
					this._lastLoginDate = value;
					this.SendPropertyChanged("lastLoginDate");
					this.OnlastLoginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastLoginIp", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string lastLoginIp
		{
			get
			{
				return this._lastLoginIp;
			}
			set
			{
				if ((this._lastLoginIp != value))
				{
					this.OnlastLoginIpChanging(value);
					this.SendPropertyChanging();
					this._lastLoginIp = value;
					this.SendPropertyChanged("lastLoginIp");
					this.OnlastLoginIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifChangePwd", DbType="Bit")]
		public System.Nullable<bool> ifChangePwd
		{
			get
			{
				return this._ifChangePwd;
			}
			set
			{
				if ((this._ifChangePwd != value))
				{
					this.OnifChangePwdChanging(value);
					this.SendPropertyChanging();
					this._ifChangePwd = value;
					this.SendPropertyChanged("ifChangePwd");
					this.OnifChangePwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="U000_B005", Storage="_B005", ThisKey="userSN", OtherKey="userSN", IsUnique=true, IsForeignKey=false)]
		public B005 B005
		{
			get
			{
				return this._B005.Entity;
			}
			set
			{
				B005 previousValue = this._B005.Entity;
				if (((previousValue != value) 
							|| (this._B005.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._B005.Entity = null;
						previousValue.U000 = null;
					}
					this._B005.Entity = value;
					if ((value != null))
					{
						value.U000 = this;
					}
					this.SendPropertyChanged("B005");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
