//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KbAPI.API.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class P0109
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string publicIp { get; set; }
        public string privateIp { get; set; }
        public string modelStr { get; set; }
        public string systemVersion { get; set; }
        public Nullable<int> modelType { get; set; }
        public string appVersion { get; set; }
        public System.DateTime useTime { get; set; }
    
        public virtual P0101 P0101 { get; set; }
    }
}
