//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KbAPI.API.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class P0101
    {
        public P0101()
        {
            this.P0102 = new HashSet<P0102>();
            this.P0109 = new HashSet<P0109>();
        }
    
        public int id { get; set; }
        public string phoneLoginEmail { get; set; }
        public int nowQuestionGroupId { get; set; }
        public int testTimes { get; set; }
        public Nullable<int> testedTimes { get; set; }
        public string constitutionType { get; set; }
        public string possibleConstitutionType { get; set; }
        public Nullable<System.DateTime> registerTime { get; set; }
        public System.DateTime lastUseTime { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
    
        public virtual ICollection<P0102> P0102 { get; set; }
        public virtual ICollection<P0109> P0109 { get; set; }
    }
}
