//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KbAPI.API.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class P0201
    {
        public int id { get; set; }
        public string questionKey { get; set; }
        public Nullable<int> sequenceId { get; set; }
        public Nullable<int> questionGroupId { get; set; }
        public Nullable<int> idInQuestionGroup { get; set; }
        public string questionContent { get; set; }
        public byte[] questionImage { get; set; }
        public Nullable<bool> calculateType { get; set; }
        public string constitutionType { get; set; }
        public Nullable<int> updateCode { get; set; }
        public Nullable<int> pVersion { get; set; }
    }
}
