#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBBC1")]
	public partial class DBBC1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertB100(B100 instance);
    partial void UpdateB100(B100 instance);
    partial void DeleteB100(B100 instance);
    partial void InsertB200(B200 instance);
    partial void UpdateB200(B200 instance);
    partial void DeleteB200(B200 instance);
    partial void InsertB300(B300 instance);
    partial void UpdateB300(B300 instance);
    partial void DeleteB300(B300 instance);
    partial void InsertB600(B600 instance);
    partial void UpdateB600(B600 instance);
    partial void DeleteB600(B600 instance);
    #endregion
		
		public DBBC1DataContext() : 
				base(global::CSL.Properties.Settings.Default.DBBC1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBBC1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBC1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBC1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBC1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<B100> B100s
		{
			get
			{
				return this.GetTable<B100>();
			}
		}
		
		public System.Data.Linq.Table<B200> B200s
		{
			get
			{
				return this.GetTable<B200>();
			}
		}
		
		public System.Data.Linq.Table<B400> B400s
		{
			get
			{
				return this.GetTable<B400>();
			}
		}
		
		public System.Data.Linq.Table<B300> B300s
		{
			get
			{
				return this.GetTable<B300>();
			}
		}
		
		public System.Data.Linq.Table<B500> B500s
		{
			get
			{
				return this.GetTable<B500>();
			}
		}
		
		public System.Data.Linq.Table<B600> B600s
		{
			get
			{
				return this.GetTable<B600>();
			}
		}
		
		public System.Data.Linq.Table<M0601> M0601s
		{
			get
			{
				return this.GetTable<M0601>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.B100")]
	public partial class B100 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userSN;
		
		private string _name;
		
		private int _cancelPublishCrAmount;
		
		private int _publishedCrAmount;
		
		private int _cancelReserveAmount;
		
		private int _refuseReserveAmount;
		
		private int _reservingCrAmount;
		
		private int _repayingCrAmount;
		
		private int _repayedCrAmount;
		
		private int _overdueAmount;
		
		private int _vipLevel;
		
		private int _needPayBillAmount;
		
		private System.Nullable<int> _clientManagerSN;
		
		private string _clientManagerWorkNum;
		
		private short _applyStatus;
		
		private System.Nullable<bool> _serverStauts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserSNChanging(string value);
    partial void OnuserSNChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncancelPublishCrAmountChanging(int value);
    partial void OncancelPublishCrAmountChanged();
    partial void OnpublishedCrAmountChanging(int value);
    partial void OnpublishedCrAmountChanged();
    partial void OncancelReserveAmountChanging(int value);
    partial void OncancelReserveAmountChanged();
    partial void OnrefuseReserveAmountChanging(int value);
    partial void OnrefuseReserveAmountChanged();
    partial void OnreservingCrAmountChanging(int value);
    partial void OnreservingCrAmountChanged();
    partial void OnrepayingCrAmountChanging(int value);
    partial void OnrepayingCrAmountChanged();
    partial void OnrepayedCrAmountChanging(int value);
    partial void OnrepayedCrAmountChanged();
    partial void OnoverdueAmountChanging(int value);
    partial void OnoverdueAmountChanged();
    partial void OnvipLevelChanging(int value);
    partial void OnvipLevelChanged();
    partial void OnneedPayBillAmountChanging(int value);
    partial void OnneedPayBillAmountChanged();
    partial void OnclientManagerSNChanging(System.Nullable<int> value);
    partial void OnclientManagerSNChanged();
    partial void OnclientManagerWorkNumChanging(string value);
    partial void OnclientManagerWorkNumChanged();
    partial void OnapplyStatusChanging(short value);
    partial void OnapplyStatusChanged();
    partial void OnserverStautsChanging(System.Nullable<bool> value);
    partial void OnserverStautsChanged();
    #endregion
		
		public B100()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSN", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userSN
		{
			get
			{
				return this._userSN;
			}
			set
			{
				if ((this._userSN != value))
				{
					this.OnuserSNChanging(value);
					this.SendPropertyChanging();
					this._userSN = value;
					this.SendPropertyChanged("userSN");
					this.OnuserSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancelPublishCrAmount", DbType="Int NOT NULL")]
		public int cancelPublishCrAmount
		{
			get
			{
				return this._cancelPublishCrAmount;
			}
			set
			{
				if ((this._cancelPublishCrAmount != value))
				{
					this.OncancelPublishCrAmountChanging(value);
					this.SendPropertyChanging();
					this._cancelPublishCrAmount = value;
					this.SendPropertyChanged("cancelPublishCrAmount");
					this.OncancelPublishCrAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishedCrAmount", DbType="Int NOT NULL")]
		public int publishedCrAmount
		{
			get
			{
				return this._publishedCrAmount;
			}
			set
			{
				if ((this._publishedCrAmount != value))
				{
					this.OnpublishedCrAmountChanging(value);
					this.SendPropertyChanging();
					this._publishedCrAmount = value;
					this.SendPropertyChanged("publishedCrAmount");
					this.OnpublishedCrAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancelReserveAmount", DbType="Int NOT NULL")]
		public int cancelReserveAmount
		{
			get
			{
				return this._cancelReserveAmount;
			}
			set
			{
				if ((this._cancelReserveAmount != value))
				{
					this.OncancelReserveAmountChanging(value);
					this.SendPropertyChanging();
					this._cancelReserveAmount = value;
					this.SendPropertyChanged("cancelReserveAmount");
					this.OncancelReserveAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refuseReserveAmount", DbType="Int NOT NULL")]
		public int refuseReserveAmount
		{
			get
			{
				return this._refuseReserveAmount;
			}
			set
			{
				if ((this._refuseReserveAmount != value))
				{
					this.OnrefuseReserveAmountChanging(value);
					this.SendPropertyChanging();
					this._refuseReserveAmount = value;
					this.SendPropertyChanged("refuseReserveAmount");
					this.OnrefuseReserveAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservingCrAmount", DbType="Int NOT NULL")]
		public int reservingCrAmount
		{
			get
			{
				return this._reservingCrAmount;
			}
			set
			{
				if ((this._reservingCrAmount != value))
				{
					this.OnreservingCrAmountChanging(value);
					this.SendPropertyChanging();
					this._reservingCrAmount = value;
					this.SendPropertyChanged("reservingCrAmount");
					this.OnreservingCrAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repayingCrAmount", DbType="Int NOT NULL")]
		public int repayingCrAmount
		{
			get
			{
				return this._repayingCrAmount;
			}
			set
			{
				if ((this._repayingCrAmount != value))
				{
					this.OnrepayingCrAmountChanging(value);
					this.SendPropertyChanging();
					this._repayingCrAmount = value;
					this.SendPropertyChanged("repayingCrAmount");
					this.OnrepayingCrAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repayedCrAmount", DbType="Int NOT NULL")]
		public int repayedCrAmount
		{
			get
			{
				return this._repayedCrAmount;
			}
			set
			{
				if ((this._repayedCrAmount != value))
				{
					this.OnrepayedCrAmountChanging(value);
					this.SendPropertyChanging();
					this._repayedCrAmount = value;
					this.SendPropertyChanged("repayedCrAmount");
					this.OnrepayedCrAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overdueAmount", DbType="Int NOT NULL")]
		public int overdueAmount
		{
			get
			{
				return this._overdueAmount;
			}
			set
			{
				if ((this._overdueAmount != value))
				{
					this.OnoverdueAmountChanging(value);
					this.SendPropertyChanging();
					this._overdueAmount = value;
					this.SendPropertyChanged("overdueAmount");
					this.OnoverdueAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipLevel", DbType="Int NOT NULL")]
		public int vipLevel
		{
			get
			{
				return this._vipLevel;
			}
			set
			{
				if ((this._vipLevel != value))
				{
					this.OnvipLevelChanging(value);
					this.SendPropertyChanging();
					this._vipLevel = value;
					this.SendPropertyChanged("vipLevel");
					this.OnvipLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_needPayBillAmount", DbType="Int NOT NULL")]
		public int needPayBillAmount
		{
			get
			{
				return this._needPayBillAmount;
			}
			set
			{
				if ((this._needPayBillAmount != value))
				{
					this.OnneedPayBillAmountChanging(value);
					this.SendPropertyChanging();
					this._needPayBillAmount = value;
					this.SendPropertyChanged("needPayBillAmount");
					this.OnneedPayBillAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerSN", DbType="Int")]
		public System.Nullable<int> clientManagerSN
		{
			get
			{
				return this._clientManagerSN;
			}
			set
			{
				if ((this._clientManagerSN != value))
				{
					this.OnclientManagerSNChanging(value);
					this.SendPropertyChanging();
					this._clientManagerSN = value;
					this.SendPropertyChanged("clientManagerSN");
					this.OnclientManagerSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerWorkNum", DbType="Char(3)")]
		public string clientManagerWorkNum
		{
			get
			{
				return this._clientManagerWorkNum;
			}
			set
			{
				if ((this._clientManagerWorkNum != value))
				{
					this.OnclientManagerWorkNumChanging(value);
					this.SendPropertyChanging();
					this._clientManagerWorkNum = value;
					this.SendPropertyChanged("clientManagerWorkNum");
					this.OnclientManagerWorkNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applyStatus", DbType="SmallInt NOT NULL")]
		public short applyStatus
		{
			get
			{
				return this._applyStatus;
			}
			set
			{
				if ((this._applyStatus != value))
				{
					this.OnapplyStatusChanging(value);
					this.SendPropertyChanging();
					this._applyStatus = value;
					this.SendPropertyChanged("applyStatus");
					this.OnapplyStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serverStauts", DbType="Bit")]
		public System.Nullable<bool> serverStauts
		{
			get
			{
				return this._serverStauts;
			}
			set
			{
				if ((this._serverStauts != value))
				{
					this.OnserverStautsChanging(value);
					this.SendPropertyChanging();
					this._serverStauts = value;
					this.SendPropertyChanged("serverStauts");
					this.OnserverStautsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.B200")]
	public partial class B200 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userSN;
		
		private string _name;
		
		private int _cancelReserveAmount;
		
		private int _refuseReserveAmount;
		
		private int _reservingCrAmount;
		
		private int _investedCrAmount;
		
		private int _closedCaseCrAmount;
		
		private int _vipLevel;
		
		private System.Nullable<int> _clientManagerSN;
		
		private string _clientManagerWorkNum;
		
		private short _applyStatus;
		
		private System.Nullable<bool> _serverStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserSNChanging(string value);
    partial void OnuserSNChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncancelReserveAmountChanging(int value);
    partial void OncancelReserveAmountChanged();
    partial void OnrefuseReserveAmountChanging(int value);
    partial void OnrefuseReserveAmountChanged();
    partial void OnreservingCrAmountChanging(int value);
    partial void OnreservingCrAmountChanged();
    partial void OninvestedCrAmountChanging(int value);
    partial void OninvestedCrAmountChanged();
    partial void OnclosedCaseCrAmountChanging(int value);
    partial void OnclosedCaseCrAmountChanged();
    partial void OnvipLevelChanging(int value);
    partial void OnvipLevelChanged();
    partial void OnclientManagerSNChanging(System.Nullable<int> value);
    partial void OnclientManagerSNChanged();
    partial void OnclientManagerWorkNumChanging(string value);
    partial void OnclientManagerWorkNumChanged();
    partial void OnapplyStatusChanging(short value);
    partial void OnapplyStatusChanged();
    partial void OnserverStatusChanging(System.Nullable<bool> value);
    partial void OnserverStatusChanged();
    #endregion
		
		public B200()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSN", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userSN
		{
			get
			{
				return this._userSN;
			}
			set
			{
				if ((this._userSN != value))
				{
					this.OnuserSNChanging(value);
					this.SendPropertyChanging();
					this._userSN = value;
					this.SendPropertyChanged("userSN");
					this.OnuserSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancelReserveAmount", DbType="Int NOT NULL")]
		public int cancelReserveAmount
		{
			get
			{
				return this._cancelReserveAmount;
			}
			set
			{
				if ((this._cancelReserveAmount != value))
				{
					this.OncancelReserveAmountChanging(value);
					this.SendPropertyChanging();
					this._cancelReserveAmount = value;
					this.SendPropertyChanged("cancelReserveAmount");
					this.OncancelReserveAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refuseReserveAmount", DbType="Int NOT NULL")]
		public int refuseReserveAmount
		{
			get
			{
				return this._refuseReserveAmount;
			}
			set
			{
				if ((this._refuseReserveAmount != value))
				{
					this.OnrefuseReserveAmountChanging(value);
					this.SendPropertyChanging();
					this._refuseReserveAmount = value;
					this.SendPropertyChanged("refuseReserveAmount");
					this.OnrefuseReserveAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservingCrAmount", DbType="Int NOT NULL")]
		public int reservingCrAmount
		{
			get
			{
				return this._reservingCrAmount;
			}
			set
			{
				if ((this._reservingCrAmount != value))
				{
					this.OnreservingCrAmountChanging(value);
					this.SendPropertyChanging();
					this._reservingCrAmount = value;
					this.SendPropertyChanged("reservingCrAmount");
					this.OnreservingCrAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_investedCrAmount", DbType="Int NOT NULL")]
		public int investedCrAmount
		{
			get
			{
				return this._investedCrAmount;
			}
			set
			{
				if ((this._investedCrAmount != value))
				{
					this.OninvestedCrAmountChanging(value);
					this.SendPropertyChanging();
					this._investedCrAmount = value;
					this.SendPropertyChanged("investedCrAmount");
					this.OninvestedCrAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closedCaseCrAmount", DbType="Int NOT NULL")]
		public int closedCaseCrAmount
		{
			get
			{
				return this._closedCaseCrAmount;
			}
			set
			{
				if ((this._closedCaseCrAmount != value))
				{
					this.OnclosedCaseCrAmountChanging(value);
					this.SendPropertyChanging();
					this._closedCaseCrAmount = value;
					this.SendPropertyChanged("closedCaseCrAmount");
					this.OnclosedCaseCrAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipLevel", DbType="Int NOT NULL")]
		public int vipLevel
		{
			get
			{
				return this._vipLevel;
			}
			set
			{
				if ((this._vipLevel != value))
				{
					this.OnvipLevelChanging(value);
					this.SendPropertyChanging();
					this._vipLevel = value;
					this.SendPropertyChanged("vipLevel");
					this.OnvipLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerSN", DbType="Int")]
		public System.Nullable<int> clientManagerSN
		{
			get
			{
				return this._clientManagerSN;
			}
			set
			{
				if ((this._clientManagerSN != value))
				{
					this.OnclientManagerSNChanging(value);
					this.SendPropertyChanging();
					this._clientManagerSN = value;
					this.SendPropertyChanged("clientManagerSN");
					this.OnclientManagerSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerWorkNum", DbType="Char(3)")]
		public string clientManagerWorkNum
		{
			get
			{
				return this._clientManagerWorkNum;
			}
			set
			{
				if ((this._clientManagerWorkNum != value))
				{
					this.OnclientManagerWorkNumChanging(value);
					this.SendPropertyChanging();
					this._clientManagerWorkNum = value;
					this.SendPropertyChanged("clientManagerWorkNum");
					this.OnclientManagerWorkNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applyStatus", DbType="SmallInt NOT NULL")]
		public short applyStatus
		{
			get
			{
				return this._applyStatus;
			}
			set
			{
				if ((this._applyStatus != value))
				{
					this.OnapplyStatusChanging(value);
					this.SendPropertyChanging();
					this._applyStatus = value;
					this.SendPropertyChanged("applyStatus");
					this.OnapplyStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serverStatus", DbType="Bit")]
		public System.Nullable<bool> serverStatus
		{
			get
			{
				return this._serverStatus;
			}
			set
			{
				if ((this._serverStatus != value))
				{
					this.OnserverStatusChanging(value);
					this.SendPropertyChanging();
					this._serverStatus = value;
					this.SendPropertyChanged("serverStatus");
					this.OnserverStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.B400")]
	public partial class B400
	{
		
		private string _userSN;
		
		private string _name;
		
		private int _refuseReserveAmount;
		
		private int _auditingCrAmount;
		
		private int _auditedCrAmount;
		
		private int _closedCrAmount;
		
		private int _vipLevel;
		
		private System.Nullable<int> _clientManagerSN;
		
		private string _clientManagerWorkNum;
		
		private short _applyStatus;
		
		private System.Nullable<bool> _serverStatus;
		
		public B400()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSN", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string userSN
		{
			get
			{
				return this._userSN;
			}
			set
			{
				if ((this._userSN != value))
				{
					this._userSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refuseReserveAmount", DbType="Int NOT NULL")]
		public int refuseReserveAmount
		{
			get
			{
				return this._refuseReserveAmount;
			}
			set
			{
				if ((this._refuseReserveAmount != value))
				{
					this._refuseReserveAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auditingCrAmount", DbType="Int NOT NULL")]
		public int auditingCrAmount
		{
			get
			{
				return this._auditingCrAmount;
			}
			set
			{
				if ((this._auditingCrAmount != value))
				{
					this._auditingCrAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auditedCrAmount", DbType="Int NOT NULL")]
		public int auditedCrAmount
		{
			get
			{
				return this._auditedCrAmount;
			}
			set
			{
				if ((this._auditedCrAmount != value))
				{
					this._auditedCrAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closedCrAmount", DbType="Int NOT NULL")]
		public int closedCrAmount
		{
			get
			{
				return this._closedCrAmount;
			}
			set
			{
				if ((this._closedCrAmount != value))
				{
					this._closedCrAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipLevel", DbType="Int NOT NULL")]
		public int vipLevel
		{
			get
			{
				return this._vipLevel;
			}
			set
			{
				if ((this._vipLevel != value))
				{
					this._vipLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerSN", DbType="Int")]
		public System.Nullable<int> clientManagerSN
		{
			get
			{
				return this._clientManagerSN;
			}
			set
			{
				if ((this._clientManagerSN != value))
				{
					this._clientManagerSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerWorkNum", DbType="Char(3)")]
		public string clientManagerWorkNum
		{
			get
			{
				return this._clientManagerWorkNum;
			}
			set
			{
				if ((this._clientManagerWorkNum != value))
				{
					this._clientManagerWorkNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applyStatus", DbType="SmallInt NOT NULL")]
		public short applyStatus
		{
			get
			{
				return this._applyStatus;
			}
			set
			{
				if ((this._applyStatus != value))
				{
					this._applyStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serverStatus", DbType="Bit")]
		public System.Nullable<bool> serverStatus
		{
			get
			{
				return this._serverStatus;
			}
			set
			{
				if ((this._serverStatus != value))
				{
					this._serverStatus = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.B300")]
	public partial class B300 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userSN;
		
		private string _name;
		
		private int _cancelReserveAmount;
		
		private int _reservingAmount;
		
		private int _purchasedAssetsAmount;
		
		private int _vipLevel;
		
		private System.Nullable<int> _clientManagerSN;
		
		private string _clientManagerWorkNum;
		
		private short _applyStatus;
		
		private System.Nullable<bool> _serverStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserSNChanging(string value);
    partial void OnuserSNChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncancelReserveAmountChanging(int value);
    partial void OncancelReserveAmountChanged();
    partial void OnreservingAmountChanging(int value);
    partial void OnreservingAmountChanged();
    partial void OnpurchasedAssetsAmountChanging(int value);
    partial void OnpurchasedAssetsAmountChanged();
    partial void OnvipLevelChanging(int value);
    partial void OnvipLevelChanged();
    partial void OnclientManagerSNChanging(System.Nullable<int> value);
    partial void OnclientManagerSNChanged();
    partial void OnclientManagerWorkNumChanging(string value);
    partial void OnclientManagerWorkNumChanged();
    partial void OnapplyStatusChanging(short value);
    partial void OnapplyStatusChanged();
    partial void OnserverStatusChanging(System.Nullable<bool> value);
    partial void OnserverStatusChanged();
    #endregion
		
		public B300()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSN", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userSN
		{
			get
			{
				return this._userSN;
			}
			set
			{
				if ((this._userSN != value))
				{
					this.OnuserSNChanging(value);
					this.SendPropertyChanging();
					this._userSN = value;
					this.SendPropertyChanged("userSN");
					this.OnuserSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancelReserveAmount", DbType="Int NOT NULL")]
		public int cancelReserveAmount
		{
			get
			{
				return this._cancelReserveAmount;
			}
			set
			{
				if ((this._cancelReserveAmount != value))
				{
					this.OncancelReserveAmountChanging(value);
					this.SendPropertyChanging();
					this._cancelReserveAmount = value;
					this.SendPropertyChanged("cancelReserveAmount");
					this.OncancelReserveAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservingAmount", DbType="Int NOT NULL")]
		public int reservingAmount
		{
			get
			{
				return this._reservingAmount;
			}
			set
			{
				if ((this._reservingAmount != value))
				{
					this.OnreservingAmountChanging(value);
					this.SendPropertyChanging();
					this._reservingAmount = value;
					this.SendPropertyChanged("reservingAmount");
					this.OnreservingAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purchasedAssetsAmount", DbType="Int NOT NULL")]
		public int purchasedAssetsAmount
		{
			get
			{
				return this._purchasedAssetsAmount;
			}
			set
			{
				if ((this._purchasedAssetsAmount != value))
				{
					this.OnpurchasedAssetsAmountChanging(value);
					this.SendPropertyChanging();
					this._purchasedAssetsAmount = value;
					this.SendPropertyChanged("purchasedAssetsAmount");
					this.OnpurchasedAssetsAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipLevel", DbType="Int NOT NULL")]
		public int vipLevel
		{
			get
			{
				return this._vipLevel;
			}
			set
			{
				if ((this._vipLevel != value))
				{
					this.OnvipLevelChanging(value);
					this.SendPropertyChanging();
					this._vipLevel = value;
					this.SendPropertyChanged("vipLevel");
					this.OnvipLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerSN", DbType="Int")]
		public System.Nullable<int> clientManagerSN
		{
			get
			{
				return this._clientManagerSN;
			}
			set
			{
				if ((this._clientManagerSN != value))
				{
					this.OnclientManagerSNChanging(value);
					this.SendPropertyChanging();
					this._clientManagerSN = value;
					this.SendPropertyChanged("clientManagerSN");
					this.OnclientManagerSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerWorkNum", DbType="Char(3)")]
		public string clientManagerWorkNum
		{
			get
			{
				return this._clientManagerWorkNum;
			}
			set
			{
				if ((this._clientManagerWorkNum != value))
				{
					this.OnclientManagerWorkNumChanging(value);
					this.SendPropertyChanging();
					this._clientManagerWorkNum = value;
					this.SendPropertyChanged("clientManagerWorkNum");
					this.OnclientManagerWorkNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applyStatus", DbType="SmallInt NOT NULL")]
		public short applyStatus
		{
			get
			{
				return this._applyStatus;
			}
			set
			{
				if ((this._applyStatus != value))
				{
					this.OnapplyStatusChanging(value);
					this.SendPropertyChanging();
					this._applyStatus = value;
					this.SendPropertyChanged("applyStatus");
					this.OnapplyStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serverStatus", DbType="Bit")]
		public System.Nullable<bool> serverStatus
		{
			get
			{
				return this._serverStatus;
			}
			set
			{
				if ((this._serverStatus != value))
				{
					this.OnserverStatusChanging(value);
					this.SendPropertyChanging();
					this._serverStatus = value;
					this.SendPropertyChanged("serverStatus");
					this.OnserverStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.B500")]
	public partial class B500
	{
		
		private int _internalUserSN;
		
		private string _workNum;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _reg_date;
		
		private System.Nullable<int> _clientTotalAmount;
		
		private System.Nullable<int> _financierAmount;
		
		private System.Nullable<int> _investorAmount;
		
		private System.Nullable<int> _consultantAmount;
		
		private System.Nullable<int> _sellerAmount;
		
		private System.Nullable<int> _purchaserAmount;
		
		public B500()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_internalUserSN", DbType="Int NOT NULL")]
		public int internalUserSN
		{
			get
			{
				return this._internalUserSN;
			}
			set
			{
				if ((this._internalUserSN != value))
				{
					this._internalUserSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workNum", DbType="Char(3)")]
		public string workNum
		{
			get
			{
				return this._workNum;
			}
			set
			{
				if ((this._workNum != value))
				{
					this._workNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reg_date", DbType="Date")]
		public System.Nullable<System.DateTime> reg_date
		{
			get
			{
				return this._reg_date;
			}
			set
			{
				if ((this._reg_date != value))
				{
					this._reg_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientTotalAmount", DbType="Int")]
		public System.Nullable<int> clientTotalAmount
		{
			get
			{
				return this._clientTotalAmount;
			}
			set
			{
				if ((this._clientTotalAmount != value))
				{
					this._clientTotalAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_financierAmount", DbType="Int")]
		public System.Nullable<int> financierAmount
		{
			get
			{
				return this._financierAmount;
			}
			set
			{
				if ((this._financierAmount != value))
				{
					this._financierAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_investorAmount", DbType="Int")]
		public System.Nullable<int> investorAmount
		{
			get
			{
				return this._investorAmount;
			}
			set
			{
				if ((this._investorAmount != value))
				{
					this._investorAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consultantAmount", DbType="Int")]
		public System.Nullable<int> consultantAmount
		{
			get
			{
				return this._consultantAmount;
			}
			set
			{
				if ((this._consultantAmount != value))
				{
					this._consultantAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sellerAmount", DbType="Int")]
		public System.Nullable<int> sellerAmount
		{
			get
			{
				return this._sellerAmount;
			}
			set
			{
				if ((this._sellerAmount != value))
				{
					this._sellerAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purchaserAmount", DbType="Int")]
		public System.Nullable<int> purchaserAmount
		{
			get
			{
				return this._purchaserAmount;
			}
			set
			{
				if ((this._purchaserAmount != value))
				{
					this._purchaserAmount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.B600")]
	public partial class B600 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userSN;
		
		private string _name;
		
		private int _cancelPublishAssetsAmount;
		
		private int _publishedAssetsAmount;
		
		private int _refuseReserveAmount;
		
		private int _reservingAssetsAmount;
		
		private int _selledAssetsAmount;
		
		private int _vipLevel;
		
		private int _needPayBillAmount;
		
		private System.Nullable<int> _clientManagerSN;
		
		private string _clientManagerWorkNum;
		
		private short _applyStatus;
		
		private System.Nullable<bool> _serverStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserSNChanging(string value);
    partial void OnuserSNChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncancelPublishAssetsAmountChanging(int value);
    partial void OncancelPublishAssetsAmountChanged();
    partial void OnpublishedAssetsAmountChanging(int value);
    partial void OnpublishedAssetsAmountChanged();
    partial void OnrefuseReserveAmountChanging(int value);
    partial void OnrefuseReserveAmountChanged();
    partial void OnreservingAssetsAmountChanging(int value);
    partial void OnreservingAssetsAmountChanged();
    partial void OnselledAssetsAmountChanging(int value);
    partial void OnselledAssetsAmountChanged();
    partial void OnvipLevelChanging(int value);
    partial void OnvipLevelChanged();
    partial void OnneedPayBillAmountChanging(int value);
    partial void OnneedPayBillAmountChanged();
    partial void OnclientManagerSNChanging(System.Nullable<int> value);
    partial void OnclientManagerSNChanged();
    partial void OnclientManagerWorkNumChanging(string value);
    partial void OnclientManagerWorkNumChanged();
    partial void OnapplyStatusChanging(short value);
    partial void OnapplyStatusChanged();
    partial void OnserverStatusChanging(System.Nullable<bool> value);
    partial void OnserverStatusChanged();
    #endregion
		
		public B600()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSN", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userSN
		{
			get
			{
				return this._userSN;
			}
			set
			{
				if ((this._userSN != value))
				{
					this.OnuserSNChanging(value);
					this.SendPropertyChanging();
					this._userSN = value;
					this.SendPropertyChanged("userSN");
					this.OnuserSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancelPublishAssetsAmount", DbType="Int NOT NULL")]
		public int cancelPublishAssetsAmount
		{
			get
			{
				return this._cancelPublishAssetsAmount;
			}
			set
			{
				if ((this._cancelPublishAssetsAmount != value))
				{
					this.OncancelPublishAssetsAmountChanging(value);
					this.SendPropertyChanging();
					this._cancelPublishAssetsAmount = value;
					this.SendPropertyChanged("cancelPublishAssetsAmount");
					this.OncancelPublishAssetsAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishedAssetsAmount", DbType="Int NOT NULL")]
		public int publishedAssetsAmount
		{
			get
			{
				return this._publishedAssetsAmount;
			}
			set
			{
				if ((this._publishedAssetsAmount != value))
				{
					this.OnpublishedAssetsAmountChanging(value);
					this.SendPropertyChanging();
					this._publishedAssetsAmount = value;
					this.SendPropertyChanged("publishedAssetsAmount");
					this.OnpublishedAssetsAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refuseReserveAmount", DbType="Int NOT NULL")]
		public int refuseReserveAmount
		{
			get
			{
				return this._refuseReserveAmount;
			}
			set
			{
				if ((this._refuseReserveAmount != value))
				{
					this.OnrefuseReserveAmountChanging(value);
					this.SendPropertyChanging();
					this._refuseReserveAmount = value;
					this.SendPropertyChanged("refuseReserveAmount");
					this.OnrefuseReserveAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservingAssetsAmount", DbType="Int NOT NULL")]
		public int reservingAssetsAmount
		{
			get
			{
				return this._reservingAssetsAmount;
			}
			set
			{
				if ((this._reservingAssetsAmount != value))
				{
					this.OnreservingAssetsAmountChanging(value);
					this.SendPropertyChanging();
					this._reservingAssetsAmount = value;
					this.SendPropertyChanged("reservingAssetsAmount");
					this.OnreservingAssetsAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selledAssetsAmount", DbType="Int NOT NULL")]
		public int selledAssetsAmount
		{
			get
			{
				return this._selledAssetsAmount;
			}
			set
			{
				if ((this._selledAssetsAmount != value))
				{
					this.OnselledAssetsAmountChanging(value);
					this.SendPropertyChanging();
					this._selledAssetsAmount = value;
					this.SendPropertyChanged("selledAssetsAmount");
					this.OnselledAssetsAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipLevel", DbType="Int NOT NULL")]
		public int vipLevel
		{
			get
			{
				return this._vipLevel;
			}
			set
			{
				if ((this._vipLevel != value))
				{
					this.OnvipLevelChanging(value);
					this.SendPropertyChanging();
					this._vipLevel = value;
					this.SendPropertyChanged("vipLevel");
					this.OnvipLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_needPayBillAmount", DbType="Int NOT NULL")]
		public int needPayBillAmount
		{
			get
			{
				return this._needPayBillAmount;
			}
			set
			{
				if ((this._needPayBillAmount != value))
				{
					this.OnneedPayBillAmountChanging(value);
					this.SendPropertyChanging();
					this._needPayBillAmount = value;
					this.SendPropertyChanged("needPayBillAmount");
					this.OnneedPayBillAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerSN", DbType="Int")]
		public System.Nullable<int> clientManagerSN
		{
			get
			{
				return this._clientManagerSN;
			}
			set
			{
				if ((this._clientManagerSN != value))
				{
					this.OnclientManagerSNChanging(value);
					this.SendPropertyChanging();
					this._clientManagerSN = value;
					this.SendPropertyChanged("clientManagerSN");
					this.OnclientManagerSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientManagerWorkNum", DbType="Char(3)")]
		public string clientManagerWorkNum
		{
			get
			{
				return this._clientManagerWorkNum;
			}
			set
			{
				if ((this._clientManagerWorkNum != value))
				{
					this.OnclientManagerWorkNumChanging(value);
					this.SendPropertyChanging();
					this._clientManagerWorkNum = value;
					this.SendPropertyChanged("clientManagerWorkNum");
					this.OnclientManagerWorkNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applyStatus", DbType="SmallInt NOT NULL")]
		public short applyStatus
		{
			get
			{
				return this._applyStatus;
			}
			set
			{
				if ((this._applyStatus != value))
				{
					this.OnapplyStatusChanging(value);
					this.SendPropertyChanging();
					this._applyStatus = value;
					this.SendPropertyChanged("applyStatus");
					this.OnapplyStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serverStatus", DbType="Bit")]
		public System.Nullable<bool> serverStatus
		{
			get
			{
				return this._serverStatus;
			}
			set
			{
				if ((this._serverStatus != value))
				{
					this.OnserverStatusChanging(value);
					this.SendPropertyChanging();
					this._serverStatus = value;
					this.SendPropertyChanged("serverStatus");
					this.OnserverStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M0601")]
	public partial class M0601
	{
		
		private string _userSN;
		
		private string _LoginName;
		
		private string _name;
		
		private int _vipLevel;
		
		private System.Nullable<decimal> _topUpAmount;
		
		private System.Nullable<decimal> _consumptionAmount;
		
		private System.Nullable<decimal> _balanceAmount;
		
		private System.Nullable<int> _needPayBillAmount;
		
		private System.Nullable<decimal> _needPayAmount;
		
		private System.Nullable<decimal> _overDueAmount;
		
		public M0601()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSN", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string userSN
		{
			get
			{
				return this._userSN;
			}
			set
			{
				if ((this._userSN != value))
				{
					this._userSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string LoginName
		{
			get
			{
				return this._LoginName;
			}
			set
			{
				if ((this._LoginName != value))
				{
					this._LoginName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipLevel", DbType="Int NOT NULL")]
		public int vipLevel
		{
			get
			{
				return this._vipLevel;
			}
			set
			{
				if ((this._vipLevel != value))
				{
					this._vipLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topUpAmount", DbType="Money")]
		public System.Nullable<decimal> topUpAmount
		{
			get
			{
				return this._topUpAmount;
			}
			set
			{
				if ((this._topUpAmount != value))
				{
					this._topUpAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consumptionAmount", DbType="Money")]
		public System.Nullable<decimal> consumptionAmount
		{
			get
			{
				return this._consumptionAmount;
			}
			set
			{
				if ((this._consumptionAmount != value))
				{
					this._consumptionAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balanceAmount", DbType="Money")]
		public System.Nullable<decimal> balanceAmount
		{
			get
			{
				return this._balanceAmount;
			}
			set
			{
				if ((this._balanceAmount != value))
				{
					this._balanceAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_needPayBillAmount", DbType="Int")]
		public System.Nullable<int> needPayBillAmount
		{
			get
			{
				return this._needPayBillAmount;
			}
			set
			{
				if ((this._needPayBillAmount != value))
				{
					this._needPayBillAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_needPayAmount", DbType="Money")]
		public System.Nullable<decimal> needPayAmount
		{
			get
			{
				return this._needPayAmount;
			}
			set
			{
				if ((this._needPayAmount != value))
				{
					this._needPayAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overDueAmount", DbType="Money")]
		public System.Nullable<decimal> overDueAmount
		{
			get
			{
				return this._overDueAmount;
			}
			set
			{
				if ((this._overDueAmount != value))
				{
					this._overDueAmount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
