//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KbAPI.API.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class P0104
    {
        public int id { get; set; }
        public int userId { get; set; }
        public System.DateTime testTime { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<int> q1 { get; set; }
        public Nullable<int> q2 { get; set; }
        public Nullable<int> q3 { get; set; }
        public Nullable<int> q4 { get; set; }
        public Nullable<int> q5 { get; set; }
        public Nullable<int> q6 { get; set; }
        public Nullable<int> q7 { get; set; }
        public Nullable<int> q8 { get; set; }
        public Nullable<int> q9 { get; set; }
        public Nullable<int> q10 { get; set; }
        public Nullable<int> q11 { get; set; }
        public Nullable<int> q12 { get; set; }
        public Nullable<int> q13 { get; set; }
        public Nullable<int> q14 { get; set; }
        public Nullable<int> q15 { get; set; }
        public Nullable<int> q16 { get; set; }
        public Nullable<int> q17 { get; set; }
        public Nullable<int> q18 { get; set; }
        public Nullable<int> q19 { get; set; }
        public Nullable<int> q20 { get; set; }
        public Nullable<int> q21 { get; set; }
        public Nullable<int> q22 { get; set; }
        public Nullable<int> q23 { get; set; }
        public Nullable<int> q24 { get; set; }
        public Nullable<int> q25 { get; set; }
        public Nullable<int> q26 { get; set; }
        public Nullable<int> q27 { get; set; }
        public Nullable<int> q28 { get; set; }
        public Nullable<int> q29 { get; set; }
        public Nullable<int> q30 { get; set; }
        public Nullable<int> q31 { get; set; }
        public Nullable<int> q32 { get; set; }
        public Nullable<int> q33 { get; set; }
        public Nullable<int> q34 { get; set; }
        public Nullable<int> q35 { get; set; }
        public Nullable<int> q36 { get; set; }
        public Nullable<int> q37 { get; set; }
        public Nullable<int> q38 { get; set; }
        public Nullable<int> q39 { get; set; }
        public Nullable<int> q40 { get; set; }
        public Nullable<int> q41 { get; set; }
        public Nullable<int> q42 { get; set; }
        public Nullable<int> q41q42 { get; set; }
        public Nullable<int> q43 { get; set; }
        public Nullable<int> q44 { get; set; }
        public Nullable<int> q45 { get; set; }
        public Nullable<int> q46 { get; set; }
        public Nullable<int> q47 { get; set; }
        public Nullable<int> q48 { get; set; }
        public Nullable<int> q49 { get; set; }
        public Nullable<int> q50 { get; set; }
        public Nullable<int> q51 { get; set; }
        public Nullable<int> q52 { get; set; }
        public Nullable<int> q53 { get; set; }
        public Nullable<int> q54 { get; set; }
        public Nullable<int> q55 { get; set; }
        public Nullable<int> q56 { get; set; }
        public Nullable<int> q57 { get; set; }
        public Nullable<int> q58 { get; set; }
        public Nullable<int> q59 { get; set; }
        public Nullable<int> q60 { get; set; }
        public Nullable<int> q61 { get; set; }
        public Nullable<int> times { get; set; }
    }
}
