//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KbAPI.API.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class P0301
    {
        public int id { get; set; }
        public int foodId { get; set; }
        public Nullable<int> type { get; set; }
        public string constitutionType { get; set; }
        public Nullable<bool> ifDelete { get; set; }
    
        public virtual P0302 P0302 { get; set; }
    }
}
